(defun color-theme-azer ()
  (interactive)
  (color-theme-install
   '(color-theme-azer
     ((background-color . "#050505")
      (background-mode . dark)
      (border-color . "white")
      (cursor-color . "#cc0000")
      (foreground-color . "white")
      (mouse-color . "white"))
     ((CUA-mode-global-mark-cursor-color . "white")
      (CUA-mode-normal-cursor-color . "white")
      (CUA-mode-overwrite-cursor-color . "white")
      (CUA-mode-read-only-cursor-color . "white")
      (help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-face . bold)
      (ps-line-number-color . "black")
      (ps-zebra-color . 0.95)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (nil))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "white"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (cursor ((t (:background "#cc0000" :foreground "#fff"))))
     (fixed-pitch ((t (:family "courier"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "#66ffff"))))
     (font-lock-comment-face ((t (:foreground "#666666"))))
     (font-lock-constant-face ((t (:foreground "#aaffff"))))
     (font-lock-doc-face ((t (:foreground "#666666"))))
     (font-lock-function-name-face ((t (:foreground "#00eeff" :weight bold :bold t))))
     (font-lock-keyword-face ((t (:foreground "#22ee11" :weight bold :bold t))))
     (font-lock-string-face ((t (:foreground "#ff3949"))))
     (font-lock-type-face ((t (:foreground "#ffee22" :bold t :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
     (font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff0000"))))
     (fringe ((t (:background "grey10"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :foreground "grey20" :background "grey90" :box nil))))
     (highlight ((t (:foreground "#ffffff" :background "#606070"))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (isearch ((t (:background "#eedd33" :foreground "#ff0000"))))
     (isearch-lazy-highlight-face ((t (:background "#eedd66"))))
     (italic ((t (:italic t :slant italic))))
     (menu ((t (nil))))
     (mode-line ((t (:foreground "White" :background "DarkRed" :box (:line-width -1 :style released-button)))))
     (mouse ((t (:background "white"))))
     (region ((t (:background "#20aaee" :foreground "#ffffff"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "#000000"))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match-face ((t (:background "turquoise"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (widget-button-face ((t (:bold t :weight bold))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "lime green"))))
     (widget-field-face ((t (:background "dim gray"))))
     (widget-inactive-face ((t (:foreground "light gray"))))
     (widget-single-line-field-face ((t (:background "dim gray")))))))

(provide 'color-theme-azer)