(require 'dircolors)
(require 'smooth-scrolling)

(load-conf-file "font.el")
(load-conf-file "core.el")
(load-conf-file "indent.el")
(load-conf-file "ui.el")
(load-conf-file "colors.el")
(load-conf-file "bindings.el")
(load-conf-file "ido.el")
(load-conf-file "markdown.el")
(load-conf-file "undo-tree.el")
(load-conf-file "term.el")
(load-conf-file "transparency.el")
